// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyTa4_ltMe9y7nS0OHFK5Ata8C7ZuV8Bc',
    appId: '1:361640124056:web:5e7800c593d5ef089c7aed',
    messagingSenderId: '361640124056',
    projectId: 'recette-plus-app',
    authDomain: 'recette-plus-app.firebaseapp.com',
    databaseURL: 'https://recette-plus-app-default-rtdb.firebaseio.com',
    storageBucket: 'recette-plus-app.firebasestorage.app',
    measurementId: 'G-GZPWYFVQ9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATXO_LRFOa-zLgYioMl7lilyiNw6cfXSQ',
    appId: '1:361640124056:android:1d8e07d0e66e6a7a9c7aed',
    messagingSenderId: '361640124056',
    projectId: 'recette-plus-app',
    databaseURL: 'https://recette-plus-app-default-rtdb.firebaseio.com',
    storageBucket: 'recette-plus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfuKmy05golMUX1FsLsuKwAWqSCnBnEmI',
    appId: '1:361640124056:ios:20106b28d05eadc39c7aed',
    messagingSenderId: '361640124056',
    projectId: 'recette-plus-app',
    databaseURL: 'https://recette-plus-app-default-rtdb.firebaseio.com',
    storageBucket: 'recette-plus-app.firebasestorage.app',
    iosClientId: '361640124056-dr8t7qea2hs2olld78lkpu0lgeulura9.apps.googleusercontent.com',
    iosBundleId: 'com.recetteplus.app',
  );
}
